name: Linux ARM64
on:
  - push
  - pull_request
jobs:
  build:
    name: build
    runs-on: ubuntu-24.04-arm
    permissions:
      id-token: write
      contents: write
      attestations: write

    steps:
      - uses: actions/checkout@v4

      - name: install deps
        run: |
          sudo apt update
          sudo apt install -y libglib2.0-dev gettext libsasl2-dev
          # We only need these to build, not to run.  Skip the dependency check.
          sudo apt download libpurple0t64 libpurple-dev
          sudo dpkg --force-depends -i libpurple0t64*.deb libpurple-dev*.deb

      - name: make
        run: |
          make
          file libircv3.so
          mv libircv3.so libircv3_arm64.so

      - name: archive
        if: github.event_name == 'push' && github.ref == 'refs/heads/main' && !env.ACT
        uses: actions/upload-artifact@v4
        with: 
            name: plugin 
            path: lib*.so

      - name: Set date
        id: date
        run: echo "DATE=$(date +%Y-%m-%d)" >> $GITHUB_OUTPUT

      - name: release
        if: github.event_name == 'push' && github.ref == 'refs/heads/main' && !env.ACT
        uses: ncipollo/release-action@v1
        with:
          artifacts: lib*.so
          tag: daily-${{ steps.date.outputs.DATE }}
          name: Daily ${{ steps.date.outputs.DATE }}
          allowUpdates: true
          makeLatest: true

      - name: attest
        if: github.event_name == 'push' && github.ref == 'refs/heads/main' && !env.ACT
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: lib*.so